#!/bin/bash
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.

# dib-lint: disable=setu setpipefail
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -e




if [ ${DISTRO_NAME} = "centos" -a ${DIB_RELEASE} -lt 8 ]; then
    # NOTE(pabelanger): We do this so we don't enable EPEL by default.
    PRE="yum -y install --enablerepo=epel golang"
    POST="yum -y remove golang"
elif [ ${DISTRO_NAME} = "centos" -a ${DIB_RELEASE} -gt 7 ]; then
    PRE="dnf -y install golang"
    POST="dnf -y remove golang"
elif [[ "$DISTRO_NAME" = "fedora" ]]; then
    PRE="dnf -y install golang"
    POST="dnf -y remove golang"
elif [[ "$DISTRO_NAME" =~ (ubuntu) ]]; then
    PRE="apt install -y golang"
    POST="apt remove -y golang"
fi

$PRE
go get -u github.com/vmware/govmomi/vcsim
mv ~/go/bin/vcsim /usr/local/bin
rm -r ~/go
$POST
